Repository open-mmlab/mmdetection, pull requests merged in 2021-05, with the labels that each got.

#5197 [Fix] Faster R-CNN fix in ONNX Runtime
  mmdet/models/dense_heads/rpn_head.py
  tools/deployment/pytorch2onnx.py
Labels: ONNX, bug

#5194 [Enhancement]: Speed up roi extractor for onnx
  mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py
Labels: ONNX

#5226 fix py3.8 dict changed during iteration
  mmdet/models/dense_heads/detr_head.py
Labels: bug

#5221 Fix AugTest of Cascade_MaskRCNN when len(det_bboxes) is 0
  mmdet/models/roi_heads/cascade_roi_head.py
Labels: bug

#5205 refactor onnx export of two stage
  mmdet/core/export/pytorch2onnx.py
  mmdet/models/dense_heads/rpn_head.py
  mmdet/models/detectors/base.py
  mmdet/models/detectors/single_stage.py
  mmdet/models/detectors/two_stage.py
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
  mmdet/models/roi_heads/mask_heads/fcn_mask_head.py
  mmdet/models/roi_heads/standard_roi_head.py
  mmdet/models/roi_heads/test_mixins.py
  tests/test_models/test_forward.py
  tests/test_models/test_roi_heads/test_bbox_head.py
  tests/test_onnx/test_head.py
Labels: deployment

#5227 Make `cat_ids` be consistent with the order of `CLASSES`
  mmdet/datasets/api_wrappers/coco_api.py
  tests/test_data/test_datasets/test_coco_dataset.py
Labels: bug

#5243 fix `get_cat_ids` of coco_api
  mmdet/datasets/api_wrappers/coco_api.py
Labels: bug

#5136 Supports for exporting CornerNet to ONNX with dynamic shapes and comparable performance
  docs/tutorials/pytorch2onnx.md
  mmdet/core/export/model_wrappers.py
  mmdet/models/backbones/hourglass.py
  mmdet/models/dense_heads/corner_head.py
  mmdet/models/detectors/single_stage.py
Labels: ONNX
