Repository open-mmlab/mmdetection, pull requests merged in 2021-08, with the labels that each got.

#5851 [Feature]: Support export onnx models without post process.
  docs/tutorials/pytorch2onnx.md
  tools/deployment/pytorch2onnx.py
Labels: deployment

#5887 [Fix] The interface `multiscale_output` is defined but not used
  mmdet/models/backbones/hrnet.py
  tests/test_models/test_backbones/test_hrnet.py
Labels: bug

#5540 [Fix] Use `warnings.warn` instead of `logger.warning`
  mmdet/models/roi_heads/point_rend_roi_head.py
  mmdet/models/roi_heads/test_mixins.py
Labels: bug

#5899 [Fix] fix a yolox bug when applying bbox rescaling in test mode (reopened)
  mmdet/models/dense_heads/yolox_head.py
Labels: bug, awaiting response

#5930 [Fix]: Fix dtype of bbox in RandomAffine.
  mmdet/datasets/pipelines/transforms.py
Labels: bug

#5952 [Feature]Add `PatchEmbed` and `PatchMerging` with `AdaptivePadding`
  mmdet/models/utils/transformer.py
  tests/test_models/test_utils/test_transformer.py
Labels: WIP
