Repository open-mmlab/mmdetection, pull requests merged in 2021-07, with the labels that each got.

#5486 Onnx cascade
  docs/tutorials/onnx2tensorrt.md
  docs/tutorials/pytorch2onnx.md
  mmdet/core/export/pytorch2onnx.py
  mmdet/core/post_processing/merge_augs.py
  mmdet/models/detectors/two_stage.py
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
  mmdet/models/roi_heads/cascade_roi_head.py
  mmdet/models/roi_heads/mask_heads/fcn_mask_head.py
  mmdet/models/roi_heads/standard_roi_head.py
  tests/test_onnx/test_head.py
  tools/deployment/pytorch2onnx.py
Labels: ONNX

#5592 The `multiclass_nms` should return the global indices.
  mmdet/core/post_processing/bbox_nms.py
Labels: bug

#5669 [WIP] Refactor YOLOX model and loss
  configs/yolox/yolox_m.py
  configs/yolox/yolox_s.py
  configs/yolox/yolox_tiny.py
  mmdet/apis/__init__.py
  mmdet/apis/cosinesnnealingwithnoaugiter_lrupdater_hook.py
  mmdet/apis/ema.py
  mmdet/apis/process_hook.py
  mmdet/core/bbox/assigners/sim_ota_assigner.py
  mmdet/datasets/mosaic_dataset.py
  mmdet/models/backbones/__init__.py
  mmdet/models/backbones/csp_darknet.py
  mmdet/models/dense_heads/yolox_head.py
  mmdet/models/losses/__init__.py
  mmdet/models/losses/iou_loss.py
  mmdet/models/necks/__init__.py
  mmdet/models/necks/yolox_pafpn.py
  mmdet/models/utils/__init__.py
  mmdet/models/utils/csp_layer.py
  tests/test_yolox_loss_tmp.py
  tools/model_converters/yolox2mmdet.py
Labels: WIP
