Repository open-mmlab/mmdetection, pull requests merged in 2021-12, with the labels that each got.

#6625 [Fix]fix init when densehead contains dcn
  mmdet/models/dense_heads/base_dense_head.py
Labels: bug

#6623 [Doc]polish docs
  mmdet/models/dense_heads/base_dense_head.py
  mmdet/models/dense_heads/rpn_head.py
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
  mmdet/models/roi_heads/bbox_heads/dii_head.py
Labels: Doc

#6622 [Fix]fix pseudosampler
  mmdet/core/bbox/samplers/pseudo_sampler.py
Labels: bug

#6663 [Fix] Fix init weights in Swin and PVT.
  mmdet/models/backbones/pvt.py
  mmdet/models/backbones/swin.py
Labels: bug

#6526 Add 'get_ann_info' to dataset_wrappers
  mmdet/datasets/dataset_wrappers.py
  tests/test_data/test_datasets/test_dataset_wrapper.py
Labels: enhancement

#6746 [Feature] Support TOOD: Task-aligned One-stage Object Detection (ICCV 2021 Oral)
  README.md
  README_zh-CN.md
  configs/tood/README.md
  configs/tood/metafile.yml
  configs/tood/tood_r101_fpn_dconv_c3-c5_mstrain_2x_coco.py
  configs/tood/tood_r101_fpn_mstrain_2x_coco.py
  configs/tood/tood_r50_fpn_1x_coco.py
  configs/tood/tood_r50_fpn_anchor_based_1x_coco.py
  configs/tood/tood_r50_fpn_mstrain_2x_coco.py
  configs/tood/tood_x101_64x4d_fpn_dconv_c4-c5_mstrain_2x_coco.py
  configs/tood/tood_x101_64x4d_fpn_mstrain_2x_coco.py
  mmdet/core/bbox/assigners/__init__.py
  mmdet/core/bbox/assigners/task_aligned_assigner.py
  mmdet/core/hook/__init__.py
  mmdet/core/hook/set_epoch_info_hook.py
  mmdet/models/dense_heads/__init__.py
  mmdet/models/dense_heads/tood_head.py
  mmdet/models/detectors/__init__.py
  mmdet/models/detectors/tood.py
  mmdet/models/losses/focal_loss.py
  mmdet/models/losses/gfocal_loss.py
  model-index.yml
  setup.cfg
  tests/test_models/test_dense_heads/test_tood_head.py
  tests/test_utils/test_assigner.py
  tests/test_utils/test_hook.py
Labels: planned feature
