Repository open-mmlab/mmdetection, pull requests merged in 2022-09, with the labels that each got.

#8663 [Docs] Update Config Doc to Add WandB Hook
  docs/en/tutorials/config.md
  docs/zh_cn/tutorials/config.md
Labels: Doc, v-2.x

#8625 [Refactor] Refactor anchor head and base head with boxlist
  mmdet/models/dense_heads/anchor_head.py
  mmdet/models/dense_heads/base_dense_head.py
  mmdet/models/dense_heads/retina_head.py
  mmdet/models/detectors/base.py
  mmdet/models/task_modules/assigners/iou2d_calculator.py
  mmdet/models/task_modules/coders/base_bbox_coder.py
  mmdet/models/task_modules/coders/bucketing_bbox_coder.py
  mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py
  mmdet/models/task_modules/coders/distance_point_bbox_coder.py
  mmdet/models/task_modules/coders/legacy_delta_xywh_bbox_coder.py
  mmdet/models/task_modules/coders/pseudo_bbox_coder.py
  mmdet/models/task_modules/coders/tblr_bbox_coder.py
  mmdet/models/task_modules/coders/yolo_bbox_coder.py
  mmdet/models/task_modules/prior_generators/anchor_generator.py
  mmdet/models/task_modules/prior_generators/utils.py
  mmdet/models/task_modules/samplers/base_sampler.py
  mmdet/models/task_modules/samplers/sampling_result.py
  mmdet/models/utils/__init__.py
  mmdet/models/utils/misc.py
  mmdet/structures/bbox/base_boxes.py
  mmdet/testing/_utils.py
  tests/test_datasets/test_transforms/test_geometric.py
  tests/test_datasets/test_transforms/test_transforms.py
  tests/test_datasets/test_transforms/utils.py
  tests/test_models/test_data_preprocessors/test_data_preprocessor.py
Labels: v-3.x

#8808 faster-rcnn README BoundedIoULoss config update [master]
  configs/faster_rcnn/README.md
Labels: v-2.x

#8805 [PR from 3.x_doc] Update FasterRCNN doc with the right URL of R-50-FPN with BoundedIoULoss
  configs/faster_rcnn/README.md
Labels: need-fix-lint

#8828 [Fix] Add list to dict keys to avoid modify loss dict
  mmdet/models/detectors/panoptic_two_stage_segmentor.py
  mmdet/models/detectors/two_stage.py
Labels: v-3.x

#8430 update analyze_results.py
  docs/en/user_guides/useful_tools.md
  tools/analysis_tools/analyze_results.py
Labels: P1, v-3.x

#8755 [Fix ] MMDetWandbHook does not support offline mode
  mmdet/core/hook/wandblogger_hook.py
Labels: enhancement, v-2.x

#8402 update analyze_logs.py
  tools/analysis_tools/analyze_logs.py
  tools/analysis_tools/get_flops.py
  tools/analysis_tools/optimize_anchors.py
Labels: P1, v-3.x

#8803 [Docs] Fix Faster R-CNN Readme
  configs/faster_rcnn/README.md
Labels: Doc, v-2.x, need-fix-conflict

#8738 Fix floordiv warning.
  mmdet/models/dense_heads/solo_head.py
  mmdet/models/dense_heads/solov2_head.py
  mmdet/models/utils/misc.py
Labels: v-3.x

#8784 Update loading.py
  mmdet/datasets/transforms/loading.py
Labels: bug, v-3.x

#8658 [Refactor] Refactor standard roi head with boxlist.
  mmdet/models/data_preprocessors/data_preprocessor.py
  mmdet/models/dense_heads/anchor_head.py
  mmdet/models/dense_heads/base_dense_head.py
  mmdet/models/dense_heads/rpn_head.py
  mmdet/models/detectors/base.py
  mmdet/models/layers/bbox_nms.py
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
  mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py
  mmdet/models/roi_heads/cascade_roi_head.py
  mmdet/models/roi_heads/standard_roi_head.py
  mmdet/models/task_modules/assigners/iou2d_calculator.py
  mmdet/models/task_modules/coders/base_bbox_coder.py
  mmdet/models/task_modules/coders/bucketing_bbox_coder.py
  mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py
  mmdet/models/task_modules/coders/distance_point_bbox_coder.py
  mmdet/models/task_modules/coders/legacy_delta_xywh_bbox_coder.py
  mmdet/models/task_modules/coders/pseudo_bbox_coder.py
  mmdet/models/task_modules/coders/tblr_bbox_coder.py
  mmdet/models/task_modules/coders/yolo_bbox_coder.py
  mmdet/models/task_modules/prior_generators/anchor_generator.py
  mmdet/models/task_modules/samplers/base_sampler.py
  mmdet/models/task_modules/samplers/sampling_result.py
  mmdet/models/utils/__init__.py
  mmdet/models/utils/misc.py
  mmdet/structures/bbox/__init__.py
  mmdet/structures/bbox/base_boxes.py
  mmdet/structures/bbox/horizontal_boxes.py
  mmdet/structures/bbox/transforms.py
  tests/test_datasets/test_transforms/test_geometric.py
  tests/test_structures/test_bbox/test_base_boxes.py
Labels: v-3.x
