Repository open-mmlab/mmdetection, pull requests merged in 2022-02, with the labels that each got.

#7032 [Fix] Keep the same weights before reassign in the PAA head
  mmdet/models/dense_heads/paa_head.py
Labels: bug

#7092 [doc] Update code demo in doc
  docs/en/2_new_data_model.md
  docs/zh_cn/2_new_data_model.md
Labels: Doc

#7020 [Feature] Support TIMMBackbone
  configs/timm_example/README.md
  configs/timm_example/retinanet_timm_efficientnet_b1_fpn_1x_coco.py
  configs/timm_example/retinanet_timm_tv_resnet50_fpn_1x_coco.py
  requirements/optional.txt
Labels: enhancement

#7041 [Feature] Support visualization for Panoptic Segmentation
  mmdet/apis/inference.py
  mmdet/core/evaluation/__init__.py
  mmdet/core/evaluation/panoptic_utils.py
  mmdet/core/mask/structures.py
  mmdet/core/visualization/image.py
  mmdet/core/visualization/palette.py
  mmdet/datasets/coco_panoptic.py
  mmdet/datasets/pipelines/__init__.py
  mmdet/datasets/utils.py
  mmdet/models/detectors/panoptic_two_stage_segmentor.py
  mmdet/models/seg_heads/panoptic_fusion_heads/heuristic_fusion_head.py
  tests/test_utils/test_visualization.py
  tools/analysis_tools/analyze_results.py
  tools/misc/browse_dataset.py
Labels: planned feature

#6823 [Feature] Support DyHead
  README.md
  README_zh-CN.md
  configs/dyhead/README.md
  configs/dyhead/atss_r50_caffe_fpn_dyhead_1x_coco.py
  configs/dyhead/atss_r50_fpn_dyhead_1x_coco.py
  configs/dyhead/metafile.yml
  mmdet/models/dense_heads/atss_head.py
  mmdet/models/necks/__init__.py
  mmdet/models/necks/dyhead.py
  mmdet/models/utils/__init__.py
  mmdet/models/utils/se_layer.py
  model-index.yml
  tests/test_models/test_necks.py
  tests/test_models/test_utils/test_se_layer.py
Labels: enhancement, planned feature

#7001 [Feature] ResNet Strikes Back.
  README.md
  README_zh-CN.md
  configs/resnet_strikes_back/README.md
  configs/resnet_strikes_back/cascade_mask_rcnn_r50_fpn_rsb-pretrain_1x_coco.py
  configs/resnet_strikes_back/faster_rcnn_r50_fpn_rsb-pretrain_1x_coco.py
  configs/resnet_strikes_back/mask_rcnn_r50_fpn_rsb-pretrain_1x_coco.py
  configs/resnet_strikes_back/metafile.yml
  configs/resnet_strikes_back/retinanet_r50_fpn_rsb-pretrain_1x_coco.py
Labels: WIP
