Repository open-mmlab/mmdetection, pull requests merged in 2022-08, with the labels that each got.

#8388 [Fix] FIx bug when evaluate with multi nodes
  configs/_base_/datasets/coco_panoptic.py
  configs/maskformer/maskformer_swin-l-p4-w12_mstrain_64x1_300e_coco.py
  mmdet/evaluation/metrics/coco_panoptic_metric.py
  tests/test_evaluation/test_metrics/test_coco_panoptic_metric.py
Labels: v-3.x

#8446 [Fix] fix LAD bug in dev-3.x
  configs/lad/lad_r101_paa_r50_fpn_coco_1x.py
  configs/lad/lad_r50_paa_r101_fpn_coco_1x.py
  mmdet/models/detectors/lad.py
Labels: v-3.x

#8457 [Fix] fix eval_mode assert error in voc metric
  mmdet/evaluation/metrics/voc_metric.py
Labels: v-3.x

#8464 [Fix] Fix EMA with pytorch1.6.
  mmdet/models/layers/ema.py
Labels: v-3.x

#8462 [Fix] fix solov2 head to support PyTorch 1.6
  mmdet/models/dense_heads/solov2_head.py
Labels: v-3.x

#8501 [Fix] Fix Shear and Translate
  mmdet/datasets/transforms/geometric.py
  tests/test_datasets/test_transforms/test_geometric.py
Labels: v-3.x

#8526 [Fix] fix ut for FliterAnnotations
  tests/test_datasets/test_transforms/test_loading.py
Labels: v-3.x

#8419 [Fix] update polygon mask and bitmap mask
  mmdet/datasets/transforms/loading.py
Labels: bug, v-3.x

#8516 [Fix] Fix memory profiler
  mmdet/engine/hooks/memory_profiler_hook.py
  tests/test_engine/test_hooks/test_memory_profiler_hook.py
Labels: v-3.x

#8435 Update confusion_matrix.py
  tools/analysis_tools/confusion_matrix.py
Labels: v-3.x

#8463 [Feature] Add a boxlist structure in mmdetection.
  mmdet/structures/bbox/__init__.py
  mmdet/structures/bbox/base_boxes.py
  mmdet/structures/bbox/box_type.py
  mmdet/structures/bbox/horizontal_boxes.py
  tests/test_structures/test_bbox/__init__.py
  tests/test_structures/test_bbox/test_base_boxes.py
  tests/test_structures/test_bbox/test_box_type.py
  tests/test_structures/test_bbox/test_horizontal_boxes.py
  tests/test_structures/test_bbox/utils.py
Labels: v-3.x

#8524 update registries
  mmdet/registry.py
Labels: v-3.x

#8490 [Feature] Random erasing
  mmdet/datasets/transforms/__init__.py
  mmdet/datasets/transforms/transforms.py
  tests/test_datasets/test_transforms/test_transforms.py
Labels: P1, v-3.x

#8503 [Feature] Support MultiValLoop
  mmdet/engine/__init__.py
  mmdet/engine/runner/__init__.py
  mmdet/engine/runner/loops.py
  tests/test_engine/test_runner/test_loops.py
Labels: P1, v-3.x

#8492 [Feature] Support MeanTeacher
  mmdet/engine/hooks/__init__.py
  mmdet/engine/hooks/mean_teacher_hook.py
  tests/test_engine/test_hooks/test_mean_teacher_hook.py
Labels: P1, v-3.x

#8494 [Feature] Support LoadEmptyAnnotations
  mmdet/datasets/transforms/__init__.py
  mmdet/datasets/transforms/loading.py
  tests/test_datasets/test_transforms/test_loading.py
Labels: P1, v-3.x

#8499 [Feature] Support ShuffledSequence
  mmdet/datasets/transforms/__init__.py
  mmdet/datasets/transforms/wrappers.py
  tests/test_datasets/test_transforms/test_wrappers.py
Labels: P1

#8495 [Feature] Support MultiDataPreprocessor
  mmdet/models/data_preprocessors/__init__.py
  mmdet/models/data_preprocessors/data_preprocessor.py
  tests/test_models/test_data_preprocessors/test_data_preprocessor.py
Labels: P1

#8597 [Fix] Clean repeated import of CascadeRPNHead
  mmdet/models/dense_heads/__init__.py
Labels: bug, v-3.x

#8562 [Refactor] Refactor pipelines with boxlist.
  mmdet/datasets/transforms/augment_wrappers.py
  mmdet/datasets/transforms/formatting.py
  mmdet/datasets/transforms/geometric.py
  mmdet/datasets/transforms/loading.py
  mmdet/datasets/transforms/transforms.py
  mmdet/models/data_preprocessors/data_preprocessor.py
  mmdet/models/utils/__init__.py
  mmdet/models/utils/misc.py
  mmdet/structures/bbox/__init__.py
  mmdet/structures/bbox/base_boxes.py
  mmdet/structures/bbox/box_type.py
  mmdet/structures/mask/structures.py
  mmdet/testing/_utils.py
  tests/test_datasets/test_transforms/test_geometric.py
  tests/test_datasets/test_transforms/test_loading.py
  tests/test_datasets/test_transforms/test_transforms.py
  tests/test_datasets/test_transforms/utils.py
  tests/test_models/test_data_preprocessors/test_data_preprocessor.py
  tests/test_structures/test_bbox/test_base_boxes.py
  tools/analysis_tools/browse_dataset.py
Labels: P0, v-3.x

#8612 correct spelling error
  mmdet/datasets/transforms/formatting.py
Labels: v-3.x

#8602 [Docs] update dataset docs
  docs/en/tutorials/customize_dataset.md
  docs/zh_cn/tutorials/customize_dataset.md
Labels: v-3.x

#8496 [Feature] Support SoftTeacher
  configs/_base_/datasets/semi_coco_detection.py
  configs/soft_teacher/README.md
  configs/soft_teacher/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.01-coco.py
  configs/soft_teacher/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.02-coco.py
  configs/soft_teacher/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.05-coco.py
  configs/soft_teacher/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.1-coco.py
  mmdet/datasets/__init__.py
  mmdet/datasets/samplers/multi_source_sampler.py
  mmdet/models/detectors/__init__.py
  mmdet/models/detectors/semi_base.py
  mmdet/models/detectors/soft_teacher.py
  tests/test_models/test_detectors/test_semi_base.py
  tools/misc/split_coco.py
Labels: P1, v-3.x

#8617 [Refactor] Fix mdformat version to support python3.6
  .pre-commit-config.yaml
  docs/en/get_started.md
  docs/zh_cn/get_started.md
  docs/zh_cn/model_zoo.md
  requirements/docs.txt
  requirements/tests.txt
Labels: v-3.x

#8565 [Docs] Refactor config tutorials for 3.x.
  docs/en/tutorials/config.md
  docs/zh_cn/tutorials/config.md
Labels: Doc, v-3.x

#8596 [Feature] Add BaseDetDataset
  mmdet/datasets/__init__.py
  mmdet/datasets/base_det_dataset.py
  mmdet/datasets/coco.py
  mmdet/datasets/lvis.py
  mmdet/datasets/openimages.py
  mmdet/datasets/xml_style.py
  mmdet/evaluation/metrics/coco_metric.py
  mmdet/evaluation/metrics/coco_panoptic_metric.py
Labels: v-3.x

#8575 [Fix]: Fix get train_pipeline method of val workflow
  tools/train.py
Labels: v-2.x

#8634 Refactor multi branch
  configs/_base_/datasets/semi_coco_detection.py
  mmdet/datasets/transforms/wrappers.py
  mmdet/models/data_preprocessors/data_preprocessor.py
  tests/test_datasets/test_transforms/test_wrappers.py
  tests/test_models/test_data_preprocessors/test_data_preprocessor.py
Labels: v-3.x

#8518 [Fix] Fix docs: new_data_model, exist_data_new_model, customize_models, customize_runtime
  docs/en/2_new_data_model.md
  docs/en/3_exist_data_new_model.md
  docs/en/tutorials/customize_models.md
  docs/en/tutorials/customize_runtime.md
  docs/zh_cn/2_new_data_model.md
  docs/zh_cn/3_exist_data_new_model.md
  docs/zh_cn/tutorials/customize_models.md
  docs/zh_cn/tutorials/customize_runtime.md
Labels: P1, Doc, v-3.x

#8637 [Fix] Fix docs:1_exist_data_model.md,how_to.md,useful_tools.md,changelog_v2.x.md,api.rst
  docs/en/ changelog_v2.x.md
  docs/en/1_exist_data_model.md
  docs/en/api.rst
  docs/en/tutorials/how_to.md
  docs/en/useful_tools.md
Labels: WIP, v-3.x

#8648 Fix floordiv warning.
  mmdet/models/dense_heads/solo_head.py
  mmdet/models/dense_heads/solov2_head.py
  mmdet/utils/misc.py
Labels: enhancement

#8652 [DOCS] Use FCOS as a rpn head in Faster R-CNN
  configs/faster_rcnn/faster-rcnn_r50_fpn_fcos-rpn_1x_coco.py
  docs/en/tutorials/customize_rpn.md
Labels: Doc, v-3.x

#8678 [Docs] Refine customize_models/customize_runtime/customize_models/how_to
  docs/en/advanced_guides/customize_models.md
  docs/en/advanced_guides/customize_runtime.md
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/customize_models.md
  docs/zh_cn/advanced_guides/customize_runtime.md
  docs/zh_cn/advanced_guides/how_to.md
Labels: Doc, v-3.x

#8681 update 3.x readme
  README.md
  README_zh-CN.md
  docs/en/overview.md
Labels: Doc, v-3.x

#8676 [Docs] fix init_cfg.md
  docs/en/user_guides/init_cfg.md
  docs/zh_cn/user_guides/init_cfg.md
Labels: Doc, v-3.x

#8677 introduce 3.x in 2.x readme
  README.md
  README_zh-CN.md
Labels: Doc, v-2.x
