Repository open-mmlab/mmdetection, pull requests merged in 2022-10, with the labels that each got.

#8437 [Feature] Add CrowdHumanDataset and Metric
  mmdet/datasets/__init__.py
  mmdet/datasets/crowdhuman.py
  mmdet/evaluation/metrics/__init__.py
  mmdet/evaluation/metrics/crowdhuman_metric.py
  tests/data/crowdhuman_dataset/id_hw_train.json
  tests/data/crowdhuman_dataset/test_annotation_train.odgt
  tests/test_datasets/test_crowdhuman.py
  tests/test_evaluation/test_metrics/test_crowdhuman_metric.py
  tools/misc/get_crowdhuman_id_hw.py
Labels: planned feature, v-3.x

#8993 [Fix] Fix bitmap mask translate when out_shape is different.
  mmdet/structures/mask/structures.py
  tests/test_structures/test_mask/test_mask_structures.py
Labels: bug, v-3.x

#8988 [Enhance] Jitter instance color.
  mmdet/visualization/__init__.py
  mmdet/visualization/local_visualizer.py
  mmdet/visualization/palette.py
  tests/test_visualization/test_palette.py
Labels: enhancement, v-3.x

#9006 [Feature] Support mask concatenate.
  mmdet/structures/mask/structures.py
  tests/test_structures/test_mask/test_mask_structures.py
Labels: enhancement, v-3.x

#8942 make compatible with `ConfigDict` and `dict`
  mmdet/models/dense_heads/anchor_head.py
  mmdet/models/dense_heads/cascade_rpn_head.py
  mmdet/models/dense_heads/gfl_head.py
  mmdet/models/dense_heads/guided_anchor_head.py
  mmdet/models/dense_heads/mask2former_head.py
  mmdet/models/dense_heads/maskformer_head.py
  mmdet/models/dense_heads/pisa_retinanet_head.py
  mmdet/models/dense_heads/reppoints_head.py
  mmdet/models/dense_heads/rtmdet_head.py
  mmdet/models/dense_heads/sabl_retina_head.py
  mmdet/models/dense_heads/yolo_head.py
  mmdet/models/dense_heads/yolox_head.py
Labels: community discussion, v-3.x

#9074 Fix bug of albumentations may return np.array or list on different versions
  mmdet/datasets/transforms/transforms.py
  tests/test_datasets/test_transforms/test_transforms.py
Labels: v-3.x

#9012 [Enhance] Log coco metric copypaste.
  mmdet/evaluation/metrics/coco_metric.py
Labels: v-3.x

#8845 Dev 3.x update dockerfile
  docker/Dockerfile
  docker/serve/Dockerfile
  docs/en/get_started.md
  docs/zh_cn/get_started.md
Labels: v-3.x

#9151 [Fix] Fix RPN visualization
  mmdet/models/detectors/rpn.py
Labels: bug, v-2.x

#9185 [Fix] Fix solov2 cannot dealing with empty gt image
  mmdet/models/dense_heads/solov2_head.py
Labels: bug, v-2.x
