Repository open-mmlab/mmdetection, pull requests merged in 2022-11, with the labels that each got.

#9192 [Fix] Fix solov2 cannot dealing with empty gt image
  mmdet/models/dense_heads/solov2_head.py
Labels: v-3.x

#9186 [Enhance] Make scipy as a default dependency in runtime
  mmdet/core/bbox/assigners/hungarian_assigner.py
  mmdet/core/bbox/assigners/mask_hungarian_assigner.py
  requirements/optional.txt
  requirements/runtime.txt
Labels: v-2.x

#9187 [Enhance] Make scipy as a default dependency in runtime
  mmdet/evaluation/metrics/crowdhuman_metric.py
  mmdet/models/task_modules/assigners/hungarian_assigner.py
  requirements/optional.txt
  requirements/runtime.txt
Labels: v-3.x

#9179 [Enhance] Add box_type support for `DynamicSoftLabelAssigner`
  mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py
  tests/test_models/test_task_modules/test_assigners/test_dynamic_soft_label_assigner.py
Labels: enhancement, v-3.x

#9015 [Fix] Fix bugs of `empty_instances` when predicting without nms in roi_head.
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
  mmdet/models/roi_heads/cascade_roi_head.py
  mmdet/models/roi_heads/standard_roi_head.py
  mmdet/models/utils/misc.py
Labels: bug, v-3.x

#8744 Add crowddet
  configs/crowddet/README.md
  configs/crowddet/crowddet-rcnn_r50_fpn_8xb2-30e_crowdhuman.py
  configs/crowddet/crowddet-rcnn_refine_r50_fpn_8xb2-30e_crowdhuman.py
  configs/crowddet/metafile.yml
  mmdet/models/data_preprocessors/__init__.py
  mmdet/models/data_preprocessors/data_preprocessor.py
  mmdet/models/detectors/__init__.py
  mmdet/models/detectors/crowddet.py
  mmdet/models/roi_heads/__init__.py
  mmdet/models/roi_heads/bbox_heads/__init__.py
  mmdet/models/roi_heads/bbox_heads/multi_instance_bbox_head.py
  mmdet/models/roi_heads/multi_instance_roi_head.py
  mmdet/models/task_modules/assigners/__init__.py
  mmdet/models/task_modules/assigners/multi_instance_assigner.py
  mmdet/models/task_modules/samplers/__init__.py
  mmdet/models/task_modules/samplers/multi_instance_random_sampler.py
  mmdet/models/task_modules/samplers/multi_instance_sampling_result.py
  tests/test_models/test_data_preprocessors/test_batch_resize.py
  tests/test_models/test_roi_heads/test_bbox_heads/test_multi_instance_bbox_head.py
  tests/test_models/test_roi_heads/test_multi_instance_roi_head.py
Labels: planned feature, v-3.x

#9207 fix mmcv-full
  configs/simple_copy_paste/mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_32xb2-ssj-270k_coco.py
  configs/simple_copy_paste/mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_32xb2-ssj-scp-270k_coco.py
  configs/strong_baselines/mask-rcnn_r50-caffe_fpn_rpn-2conv_4conv1fc_syncbn-all_lsj-100e_coco.py
  configs/strong_baselines/mask-rcnn_r50_fpn_rpn-2conv_4conv1fc_syncbn-all_lsj-100e_coco.py
Labels: v-3.x

#9241 [Fix] Fix dump results.
  mmdet/utils/__init__.py
  mmdet/utils/misc.py
  tools/analysis_tools/test_robustness.py
  tools/test.py
Labels: bug, v-3.x

#9058 [Fix] Add `ignore_key` in voc dataset to fix error
  configs/_base_/datasets/voc0712.py
  configs/pascal_voc/ssd300_voc0712.py
  configs/pascal_voc/ssd512_voc0712.py
  mmdet/__init__.py
Labels: pending

#9259 [Fix]: fix (Cached) MixUp padding
  mmdet/datasets/transforms/transforms.py
Labels: v-3.x

#9287 [Fix] Fix resume arg conflict.
  tools/train.py
Labels: bug, v-3.x

#9358 [Fix] Fix bbox refine bug with sigmoid activation.
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
Labels: bug, v-3.x

#9276 [Feature] save config file in print_config.py
  tools/misc/print_config.py
Labels: v-3.x

#9177 [DOCS] Fix doc typos in MMDetection 3.x(useful tools)
  docs/en/user_guides/useful_hooks.md
  docs/zh_cn/user_guides/useful_hooks.md
  docs/zh_cn/user_guides/useful_tools.md
Labels: v-3.x

#9376 [Fix] Fix mmdet.utils.typing error in CondInst
  mmdet/models/detectors/condinst.py
Labels: bug, v-3.x

#9292 add faq
  docs/en/notes/faq.md
  docs/zh_cn/notes/faq.md
Labels: Doc, v-3.x

#9400 [Fix] Fix Condinst predict error when val batch_size>1
  mmdet/models/dense_heads/condinst_head.py
Labels: bug, v-3.x
