Repository open-mmlab/mmdetection, pull requests merged in 2022-01, with the labels that each got.

#6951 change compose.__repr__() to make indent precisely
  mmdet/datasets/pipelines/compose.py
Labels: enhancement

#6956 Fix typo in mmdet.datasets.pipelines.formating
  mmdet/datasets/pipelines/__init__.py
  mmdet/datasets/pipelines/formating.py
  mmdet/datasets/pipelines/formatting.py
Labels: refactor

#6974 [Enhance] Continue to speed up training.
  configs/_base_/default_runtime.py
  tools/train.py
Labels: enhancement

#6966 Fix BadZipFile Error when build docker
  docker/Dockerfile
Labels: installation/env

#7003 promote to use mmdeploy
  docs/en/tutorials/onnx2tensorrt.md
  docs/en/tutorials/pytorch2onnx.md
  docs/zh_cn/tutorials/onnx2tensorrt.md
  docs/zh_cn/tutorials/pytorch2onnx.md
Labels: Doc

#7015 [Feature]Add coco, lvis and voc dataset download script based on pr #6715
  docs/en/1_exist_data_model.md
  docs/en/useful_tools.md
  docs/zh_cn/1_exist_data_model.md
  tools/misc/download_dataset.py
Labels: enhancement, planned feature

#7064 [Fix] Put the `mAP` at the front of OrderedDict in VOCDataset
  mmdet/datasets/voc.py
Labels: enhancement

#6985 Add Overview of Benchmark and Model Zoo
  README.md
Labels: Doc

#7074 [Fix] Fix bbox clamp in pt1.10
  mmdet/models/dense_heads/autoassign_head.py
  mmdet/models/dense_heads/fcos_head.py
Labels: bug

#7085 [Fix] Relax the requirement of PALETTE in dataset wrappers
  mmdet/datasets/dataset_wrappers.py
  tests/test_data/test_datasets/test_dataset_wrapper.py
Labels: bug
