Repository open-mmlab/mmdetection, pull requests merged in 2022-03, with the labels that each got.

#7270 Fix VOC unit test not to remove data directory
  .github/workflows/build.yml
  tests/test_data/test_datasets/test_common.py
Labels: bug

#7301 update readme and pretrained related
  README.md
  tools/test.py
Labels: Doc

#7328 [Fix] set unmap_results=True in ssd_head
  mmdet/models/dense_heads/ssd_head.py
Labels: size/XS

#7315 [Enhance] add cpu_num in cocopanoptic for pq computing
  mmdet/datasets/api_wrappers/panoptic_evaluation.py
  mmdet/datasets/coco_panoptic.py
Labels: size/XS

#7324 [Fix] Force the inputs of `get_bboxes` in yolox_head to float32.
  mmdet/models/dense_heads/centripetal_head.py
  mmdet/models/dense_heads/corner_head.py
  mmdet/models/dense_heads/yolox_head.py
Labels: size/XS

#7388 [Fix] new params misplaced in loadannotation
  mmdet/datasets/pipelines/loading.py
Labels: size/XS

#7313 [Feature] add instance evalutation in coco_panoptic
  mmdet/apis/test.py
  mmdet/datasets/coco.py
  mmdet/datasets/coco_panoptic.py
  tests/test_data/test_datasets/test_panoptic_dataset.py
Labels: enhancement, size/XS

#7432 [Feature] Add diff seeds to diff ranks.
  mmdet/core/utils/__init__.py
  mmdet/core/utils/dist_utils.py
  mmdet/datasets/builder.py
  mmdet/datasets/samplers/distributed_sampler.py
  mmdet/datasets/samplers/infinite_sampler.py
  tools/train.py
Labels: size/XS

#7407 Enhance the robustness of analyze_logs.py
  tools/analysis_tools/analyze_logs.py
Labels: size/XS

#7440 [Enchance] Supplementary notes of sync_random_seed
  mmdet/core/utils/dist_utils.py
  mmdet/datasets/samplers/distributed_sampler.py
  mmdet/datasets/samplers/infinite_sampler.py
Labels: size/XS

#7456 [Enchance] Unified name of orig as ori
  mmdet/datasets/pipelines/instaboost.py
  mmdet/datasets/pipelines/transforms.py
  tools/analysis_tools/get_flops.py
Labels: size/XS

#7480 Remove duplicate link
  docs/en/projects.md
Labels: size/XS

#7472 [Enhance] Update docstring of cross entropy loss
  mmdet/models/losses/cross_entropy_loss.py
Labels: size/XS

#7438 [Enchance] Added documentation on mmdet using mmcls‘s backbone
  docs/en/tutorials/how_to.md
  docs/en/tutorials/index.rst
  docs/zh_cn/tutorials/how_to.md
  docs/zh_cn/tutorials/index.rst
Labels: size/XS

#7498 Update README.md
  README.md
Labels: size/XS

#7510 Frozen misspelled in docs
  configs/selfsup_pretrain/README.md
  docs/en/tutorials/config.md
Labels: size/XS

#7507 update-mosaic-to-how-to
  docs/en/tutorials/how_to.md
  docs/zh_cn/tutorials/how_to.md
Labels: size/XS

#7521 Bug fix: RuntimeError: Expected all tensors to be on the same device,…
  mmdet/models/dense_heads/free_anchor_retina_head.py
Labels: bug, size/XS

#7489 [Feature] Torchvision high-precision ResNet model
  configs/faster_rcnn/README.md
  configs/faster_rcnn/faster_rcnn_r50_fpn_tnr-pretrain_1x_coco.py
  configs/faster_rcnn/metafile.yml
Labels: size/XS

#7466 [Feature] Support MSDeform attn pixel decoder
  mmdet/models/plugins/__init__.py
  mmdet/models/plugins/msdeformattn_pixel_decoder.py
  mmdet/models/plugins/pixel_decoder.py
  tests/test_models/test_plugins.py
Labels: size/XS

#7471 [Enhance] MaskFormer refactor
  configs/maskformer/maskformer_r50_mstrain_16x1_75e_coco.py
  mmdet/core/mask/__init__.py
  mmdet/core/mask/utils.py
  mmdet/models/dense_heads/maskformer_head.py
  mmdet/models/detectors/maskformer.py
  mmdet/models/seg_heads/panoptic_fusion_heads/__init__.py
  mmdet/models/seg_heads/panoptic_fusion_heads/maskformer_fusion_head.py
  tests/test_models/test_dense_heads/test_maskformer_head.py
  tests/test_models/test_seg_heads/test_maskformer_fusion_head.py
  tests/test_utils/test_masks.py
Labels: size/XXL

#7514 [Feature] Support efficientnet in mmdetection.
  configs/efficientnet/README.md
  configs/efficientnet/metafile.yml
  configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco.py
  mmdet/models/backbones/__init__.py
  mmdet/models/backbones/efficientnet.py
  mmdet/models/utils/inverted_residual.py
  model-index.yml
  tests/test_models/test_backbones/test_efficientnet.py
Labels: size/XS

#7449 [Fix] Fix reduction=mean in CELoss.
  mmdet/models/dense_heads/free_anchor_retina_head.py
  mmdet/models/losses/cross_entropy_loss.py
  mmdet/models/losses/utils.py
  tests/test_models/test_loss.py
Labels: bug

#7386 [Feature] Support to set data root through commands
  docs/en/3_exist_data_new_model.md
  docs/zh_cn/3_exist_data_new_model.md
  mmdet/utils/__init__.py
  mmdet/utils/misc.py
  tools/analysis_tools/analyze_results.py
  tools/analysis_tools/benchmark.py
  tools/analysis_tools/confusion_matrix.py
  tools/analysis_tools/eval_metric.py
  tools/analysis_tools/optimize_anchors.py
  tools/misc/browse_dataset.py
  tools/misc/print_config.py
  tools/test.py
  tools/train.py
Labels: size/XS

#6938 [Feature] add Mask2former to mmdet
  configs/mask2former/mask2former_r50_lsj_8x2_50e_coco.py
  configs/mask2former/mask2former_swin-t-p4-w7-224_lsj_8x2_50e_coco.py
  mmdet/core/bbox/match_costs/__init__.py
  mmdet/core/bbox/match_costs/match_cost.py
  mmdet/datasets/coco.py
  mmdet/datasets/coco_panoptic.py
  mmdet/models/dense_heads/__init__.py
  mmdet/models/dense_heads/mask2former_head.py
  mmdet/models/detectors/__init__.py
  mmdet/models/detectors/mask2former.py
  tests/test_models/test_dense_heads/test_mask2former_head.py
  tests/test_models/test_forward.py
  tests/test_utils/test_assigner.py
Labels: enhancement, planned feature

#7537 [Fix] Update unit test of CrossEntropyCost
  tests/test_utils/test_assigner.py
Labels: size/XS

#7551 fix broadcast shape bug in yolov3
  mmdet/models/losses/cross_entropy_loss.py
Labels: size/XS

#7550 Fix `pointrend` missing `get_uncertainty` function bug
  mmdet/models/roi_heads/mask_heads/mask_point_head.py
  mmdet/models/utils/__init__.py
Labels: size/XXL

#7547 fix docstring in bbox_nms.py
  mmdet/core/post_processing/bbox_nms.py
Labels: size/XS

#7430 [Doc] Add doc for COCO panoptic segmentation test results submission
  docs/en/tutorials/test_results_submission.md
  tools/misc/gen_coco_panoptic_test_info.py
Labels: size/XS

#7555 Bump versions to v2.23.0
  README.md
  README_zh-CN.md
  docker/serve/Dockerfile
  docs/en/changelog.md
  docs/en/get_started.md
  docs/en/model_zoo.md
  docs/zh_cn/get_started.md
  mmdet/version.py
Labels: size/XS

#7582 [Fix]the master branch of pre-commit-hooks may be unstable
  .pre-commit-config.yaml
Labels: size/XS

#7575 Update from-scratch install script in get_started.md
  docs/en/get_started.md
  docs/zh_cn/get_started.md
Labels: size/XS

#7591 Fix a minor typo in data_pipeline docs
  docs/en/tutorials/data_pipeline.md
Labels: size/XS

#7549 [Doc] How to train fast_rcnn model.
  configs/fast_rcnn/README.md
Labels: size/XS
