Repository open-mmlab/mmdetection, pull requests merged in 2022-12, with the labels that each got.

#9469 [Refactor] Refactor dataset metainfo to lowercase.
  configs/_base_/datasets/voc0712.py
  configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person-bicycle-car.py
  configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person.py
  configs/pascal_voc/faster-rcnn_r50_fpn_1x_voc0712-cocofmt.py
  configs/pascal_voc/ssd300_voc0712.py
  configs/pascal_voc/ssd512_voc0712.py
  docs/en/advanced_guides/customize_dataset.md
  docs/en/advanced_guides/customize_runtime.md
  docs/en/user_guides/train.md
  docs/zh_cn/advanced_guides/customize_dataset.md
  docs/zh_cn/advanced_guides/customize_runtime.md
  docs/zh_cn/user_guides/train.md
  mmdet/apis/inference.py
  mmdet/datasets/cityscapes.py
  mmdet/datasets/coco.py
  mmdet/datasets/coco_panoptic.py
  mmdet/datasets/crowdhuman.py
  mmdet/datasets/deepfashion.py
  mmdet/datasets/lvis.py
  mmdet/datasets/openimages.py
  mmdet/datasets/samplers/class_aware_sampler.py
  mmdet/datasets/voc.py
  mmdet/datasets/wider_face.py
  mmdet/datasets/xml_style.py
  mmdet/engine/hooks/num_class_check_hook.py
  mmdet/evaluation/metrics/cityscapes_metric.py
  mmdet/evaluation/metrics/coco_metric.py
  mmdet/evaluation/metrics/coco_panoptic_metric.py
  mmdet/evaluation/metrics/openimages_metric.py
  mmdet/evaluation/metrics/voc_metric.py
  mmdet/visualization/local_visualizer.py
  mmdet/visualization/palette.py
  tests/test_datasets/test_cityscapes.py
  tests/test_datasets/test_coco.py
  tests/test_datasets/test_coco_panoptic.py
  tests/test_datasets/test_crowdhuman.py
  tests/test_datasets/test_lvis.py
  tests/test_datasets/test_openimages.py
  tests/test_engine/test_hooks/test_num_class_check_hook.py
  tests/test_evaluation/test_metrics/test_cityscapes_metric.py
  tests/test_evaluation/test_metrics/test_coco_metric.py
  tests/test_evaluation/test_metrics/test_coco_panoptic_metric.py
  tests/test_evaluation/test_metrics/test_lvis_metric.py
  tests/test_visualization/test_local_visualizer.py
  tests/test_visualization/test_palette.py
  tools/analysis_tools/analyze_results.py
  tools/analysis_tools/confusion_matrix.py
  tools/deployment/mmdet_handler.py
Labels: refactor, v-3.x

#9479 [Refactor] Remove legacy builder.py
  .dev_scripts/test_init_backbone.py
  mmdet/apis/inference.py
  mmdet/datasets/__init__.py
  mmdet/datasets/builder.py
  mmdet/models/__init__.py
  mmdet/models/builder.py
  mmdet/models/dense_heads/centripetal_head.py
  mmdet/models/dense_heads/corner_head.py
  mmdet/models/dense_heads/solov2_head.py
  mmdet/models/detectors/solov2.py
  mmdet/models/roi_heads/mask_heads/mask_point_head.py
  mmdet/utils/benchmark.py
  tests/test_models/test_detectors/test_cornernet.py
  tests/test_models/test_detectors/test_kd_single_stage.py
  tests/test_models/test_detectors/test_maskformer.py
  tests/test_models/test_detectors/test_panoptic_two_stage_segmentor.py
  tests/test_models/test_detectors/test_rpn.py
  tests/test_models/test_detectors/test_single_stage.py
  tests/test_models/test_detectors/test_single_stage_instance_seg.py
  tests/test_models/test_detectors/test_two_stage.py
  tests/test_models/test_task_modules/test_prior_generators/test_anchor_generator.py
  tools/analysis_tools/optimize_anchors.py
Labels: refactor, v-3.x

#9494 [Feature] Support RTMDet-Ins and improve RTMDet test config.
  README.md
  README_zh-CN.md
  configs/rtmdet/README.md
  configs/rtmdet/metafile.yml
  configs/rtmdet/rtmdet-ins_l_8xb32-300e_coco.py
  configs/rtmdet/rtmdet-ins_m_8xb32-300e_coco.py
  configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py
  configs/rtmdet/rtmdet-ins_tiny_8xb32-300e_coco.py
  configs/rtmdet/rtmdet-ins_x_8xb16-300e_coco.py
  configs/rtmdet/rtmdet_l_8xb32-300e_coco.py
  mmdet/datasets/transforms/transforms.py
  mmdet/models/dense_heads/__init__.py
  mmdet/models/dense_heads/rtmdet_head.py
  mmdet/models/dense_heads/rtmdet_ins_head.py
  mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py
  setup.cfg
Labels: planned feature, v-3.x

#9324 [BC Breaking] Make sure the pipeline input shape is in WH order
  configs/yolox/yolox_s_8xb8-300e_coco.py
  configs/yolox/yolox_tiny_8xb8-300e_coco.py
  docs/en/advanced_guides/conventions.md
  docs/zh_cn/advanced_guides/conventions.md
  mmdet/datasets/transforms/formatting.py
  mmdet/datasets/transforms/transforms.py
  tests/test_datasets/test_transforms/test_transforms.py
Labels: v-3.x
