Repository open-mmlab/mmdetection, pull requests merged in 2023-02, with the labels that each got.

#9143 [Feature] Support auto import modules from registry.
  configs/convnext/cascade-mask-rcnn_convnext-s-p4-w7_fpn_4conv1fc-giou_amp-ms-crop-3x_coco.py
  configs/convnext/cascade-mask-rcnn_convnext-t-p4-w7_fpn_4conv1fc-giou_amp-ms-crop-3x_coco.py
  configs/convnext/mask-rcnn_convnext-t-p4-w7_fpn_amp-ms-crop-3x_coco.py
  configs/rtmdet/classification/cspnext-s_8xb256-rsb-a1-600e_in1k.py
  configs/timm_example/retinanet_timm-efficientnet-b1_fpn_1x_coco.py
  configs/timm_example/retinanet_timm-tv-resnet50_fpn_1x_coco.py
  demo/image_demo.py
  demo/video_demo.py
  demo/video_gpuaccel_demo.py
  demo/webcam_demo.py
  docs/en/get_started.md
  docs/en/notes/faq.md
  docs/en/user_guides/inference.md
  docs/zh_cn/get_started.md
  docs/zh_cn/notes/faq.md
  mmdet/__init__.py
  mmdet/apis/inference.py
  mmdet/registry.py
  requirements/mminstall.txt
  tools/analysis_tools/analyze_results.py
  tools/analysis_tools/benchmark.py
  tools/analysis_tools/browse_dataset.py
  tools/analysis_tools/confusion_matrix.py
  tools/analysis_tools/eval_metric.py
  tools/analysis_tools/get_flops.py
  tools/analysis_tools/optimize_anchors.py
  tools/analysis_tools/test_robustness.py
  tools/deployment/mmdet_handler.py
  tools/deployment/test_torchserver.py
  tools/test.py
  tools/train.py
Labels: enhancement, v-3.x

#9734 [Fix] Fix WIDERFace SSD loss NAN.
  configs/wider_face/ssd300_wider_face.py
Labels: bug, v-2.x

#9710 [Feature] Migrate occluded metric to 3.x.
  docs/en/user_guides/useful_tools.md
  docs/zh_cn/user_guides/useful_tools.md
  mmdet/evaluation/metrics/__init__.py
  mmdet/evaluation/metrics/coco_metric.py
  mmdet/evaluation/metrics/coco_occluded_metric.py
  mmdet/evaluation/metrics/dump_det_results.py
  tests/test_evaluation/test_metrics/test_coco_occluded_metric.py
  tests/test_evaluation/test_metrics/test_dump_det_results.py
  tools/analysis_tools/coco_occluded_separated_recall.py
  tools/test.py
Labels: v-3.x

#9635 Add benchmark model files
  .dev_scripts/benchmark_full_models.txt
  .dev_scripts/benchmark_options.py
  .dev_scripts/benchmark_train_models.txt
Labels: pending
