Repository open-mmlab/mmdetection, pull requests merged in 2023-01, with the labels that each got.

#9445 [Enhance] Support modifying palette through configuration
  demo/image_demo.py
  mmdet/apis/inference.py
Labels: v-3.x

#7525 [Feature] Support Objects365 Dataset
  .dev_scripts/gather_models.py
  configs/_base_/datasets/objects365v1_detection.py
  configs/_base_/datasets/objects365v2_detection.py
  configs/objects365/README.md
  configs/objects365/faster_rcnn_r50_fpn_16x4_1x_obj365v1.py
  configs/objects365/faster_rcnn_r50_fpn_16x4_1x_obj365v2.py
  configs/objects365/faster_rcnn_r50_fpn_syncbn_1350k_obj365v1.py
  configs/objects365/metafile.yml
  configs/objects365/retinanet_r50_fpn_1x_obj365v1.py
  configs/objects365/retinanet_r50_fpn_1x_obj365v2.py
  configs/objects365/retinanet_r50_fpn_syncbn_1350k_obj365v1.py
  mmdet/core/evaluation/__init__.py
  mmdet/core/evaluation/class_names.py
  mmdet/datasets/__init__.py
  mmdet/datasets/objects365.py
  tests/test_data/test_datasets/test_objects365.py
  tools/misc/download_dataset.py
Labels: size/XS

#9624 [Fix] Fix use_depthwise in RTMDet.
  mmdet/models/dense_heads/rtmdet_head.py
  mmdet/models/necks/cspnext_pafpn.py
Labels: bug

#9619 [Feature] Support ConvNeXt-V2.
  projects/ConvNeXt-V2/README.md
  projects/ConvNeXt-V2/configs/mask-rcnn_convnext-v2-b_fpn_lsj-3x-fcmae_coco.py
Labels: planned feature, v-3.x

#9600 [Feature] Support Objects365 Dataset
  .dev_scripts/gather_models.py
  configs/_base_/datasets/objects365v1_detection.py
  configs/_base_/datasets/objects365v2_detection.py
  configs/objects365/README.md
  configs/objects365/faster-rcnn_r50-syncbn_fpn_1350k_objects365v1.py
  configs/objects365/faster-rcnn_r50_fpn_16xb4-1x_objects365v1.py
  configs/objects365/faster-rcnn_r50_fpn_16xb4-1x_objects365v2.py
  configs/objects365/metafile.yml
  configs/objects365/retinanet_r50-syncbn_fpn_1350k_objects365v1.py
  configs/objects365/retinanet_r50_fpn_1x_objects365v1.py
  configs/objects365/retinanet_r50_fpn_1x_objects365v2.py
  mmdet/datasets/__init__.py
  mmdet/datasets/objects365.py
  mmdet/evaluation/functional/__init__.py
  mmdet/evaluation/functional/class_names.py
  mmdet/evaluation/metrics/coco_metric.py
  tests/data/Objects365/unsorted_obj365_sample.json
  tests/test_datasets/test_objects365.py
  tools/misc/download_dataset.py
Labels: v-3.x

#9574 [Feature] Support Separated and Occluded COCO metric.
  docs/en/useful_tools.md
  mmdet/datasets/__init__.py
  mmdet/datasets/coco_occluded.py
  tests/test_data/test_datasets/test_coco_occluded.py
  tools/analysis_tools/coco_occluded_separated_recall.py
Labels: planned feature, v-2.x

#9645 [Projects] Support Detic inference.
  mmdet/models/roi_heads/bbox_heads/bbox_head.py
  mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py
  projects/Detic/README.md
  projects/Detic/configs/detic_centernet2_swin-b_fpn_4x_lvis-coco-in21k.py
  projects/Detic/demo.py
  projects/Detic/detic/__init__.py
  projects/Detic/detic/centernet_rpn_head.py
  projects/Detic/detic/detic_bbox_head.py
  projects/Detic/detic/detic_roi_head.py
  projects/Detic/detic/text_encoder.py
  projects/Detic/detic/utils.py
  projects/Detic/detic/zero_shot_classifier.py
Labels: planned feature, v-3.x
